### PR TITLE
Improve comment handling for maps and sequences

### PR DESCRIPTION
**Pull request by felixfontein**
Extends the comment hack by @autrilla to improve handling of comments in maps and sequences. Also adds a unit test.

Should fix the "comment crawl" problem I reported in mozilla/sops#695.

### CODE REVIEW

**Review by autrilla — APPROVED** [review]
LGTM. Perhaps the only change I'd want is a better name for `tmpSlice`, and ideally some comments about what it's used for. My understanding is that it's used to hold comments that appear before the first key in a mapping, and then those are flushed at the beginning of the next sequence or at the end of the next mapping. Or, if encountered while parsing a mapping and we have time to emit it before the mapping ends, then emitted in the same mapping.

**Comment by autrilla** [comment]
Also, thanks a lot for contributing this change. Having worked on this library, I know it's definitely not the easiest code to navigate and I'm very happy to see someone who's not a regular sops contributor take a stab at this very nontrivial task.

**Comment by felixfontein** [comment]
@autrilla `tmpSlice` is indeed not the best name ;) I've changed it to `prependComments`. I've also added a short comment on what it does.

**Comment by autrilla** [comment]
Thanks a lot again :)

**Comment by felixfontein** [comment]
@autrilla also thanks a lot for your help, and for creating comment support for YAML in sops in the first place!

**Pull request merged**
